### ISSUE TITLE
-h Command Not Working

### ISSUE THREAD

**Issue by emily-desverreaux** [2bdenny/ReScue#1]
Hi,

I have noticed that your GitHub readme says that the -h command can be used for the .jar file, which can be found at this [link](https://github.com/2bdenny/ReScue/blob/master/release/Readme.txt). The readme states :  
java -jar rescue.jar -h
Show this text.

This, however, is not available within the project. Here is an example of my -h output:
`emily@snoopy:~/Desktop/2bdenny-ReScue-ecf0e98/release$ java -jar ReScue.jar -h
java.nio.file.NoSuchFileException: configs/usage/usage.txt
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
    at java.nio.file.Files.newInputStream(Files.java:152)
    at java.nio.file.Files.newBufferedReader(Files.java:2784)
    at java.nio.file.Files.readAllLines(Files.java:3202)
    at java.nio.file.Files.readAllLines(Files.java:3242)
    at cn.edu.nju.moon.redos.tester.RedosTester.main(RedosTester.java:41)`

Is it possible that you uploaded the wrong version of the jar file? If so, could you please correct this? The readme says that this command should work.

Thank you.

**Comment by 2bdenny** [comment]
Yes, I uploaded a wrong version jar file (which need a `usage.txt` file to show the help message, someone told me that `config-free` would be better for users, so I just deleted the usage file, and forgot to update the release jar...)

I have uploaded the release jar of the right version, thanks for your reporting =D
